### ISSUE TITLE
Destructuring Assignment

### ISSUE THREAD

**Issue by herberthenrique** [raulmangolin/mango-reactions#4]
Apply on options

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by persocon** [comment]
example where we could add that please

**Comment by herberthenrique** [comment]
Sorry, i was talking to mangolin that i should give a better description
https://github.com/raulmangolin/mango-reactions/blob/master/src/reactions.js#L10

I was reading the code and the object `defaults` have 7 properties but is only used two.
`url` and `refreshTime`

**Comment by persocon** [comment]
it actually uses none, I mean, I pass the default.url to the message.push, but that's it only.
it's purpose is to pass itself for the return in case the user don't put any options, but it's dumb at all because it raises an error if the user don't passes the needed options.

it's kinda of a redundant thing, and to prevent reassignment too. we could cut that to just the ones really needed for the app to work of without the user passes options... OR remove at all the defaults and keep just the url and refreshTime.

**Comment by persocon** [comment]
fixed on #9 (Patch-2)
@raulmangolin close later please :)

**Comment by herberthenrique** [comment]
Perfect :)
